---
- name: Repo Configuration
  hosts: all
  gather_facts: false # remove later! speeds up testing
  become: true

  tasks:
  - name: enable repos
    template:
      src: ./templates/open_three-tier-app.repo.j2
      dest: /etc/yum.repos.d/open_three-tier-app.repo
      mode: 0644

- name: Install HA Proxy
  hosts: frontends
  become: ture
  roles:
    - { role: geerlingguy.haproxy }

- name: Install Tomcat
  hosts: apps
  become: true
  roles:
    - { role: app-tomcat }

       
- name: Deploy Postgres to AppDB servers
  hosts: appdbs
  become: true
  roles:
    - { role: geerlingguy.postgres }
...